# Predicting the real mortality rate for COVID-19

In this notebook, we attempt to predict the mortality rate for COVID-19 (the "new coronavirus") while controlling for country-level covariates such as access to healthcare and age of population.

In [4]:
import warnings
warnings.simplefilter('ignore')

from source import data

In [5]:
df = data.get_all_data()

In [6]:
df.head(10)

,cases,deaths,death_rate_observed,days_since_first_case,cpi_score_2019,healthcare_spending_per_capita,hci,physicians_per_capita,population_perc_over65,population_perc_rural
Country/Region,,,,,,,,,,
Afghanistan,4,0,0.000000,14,16,57.248760,0.389,0.2840,2.584927,74.505
Albania,2,0,0.000000,0,35,271.543043,0.621,1.1998,13.744736,39.681
Algeria,20,0,0.000000,13,35,260.412579,0.523,1.8300,6.362497,27.371
Argentina,12,1,0.083333,6,45,955.200949,0.611,NaN,11.117789,8.130
Armenia,1,0,0.000000,8,42,358.841748,0.572,NaN,11.253818,36.851
Australia,91,4,0.043956,43,77,5002.358277,0.803,3.5874,15.656475,13.988
Austria,131,0,0.000000,13,77,4688.280204,0.793,5.1441,19.001566,41.703
Azerbaijan,9,0,0.000000,8,30,268.155865,0.597,NaN,6.195183,44.320
Bahrain,95,0,0.000000,14,42,1099.362291,0.668,NaN,2.426334,10.713
Bangladesh,3,0,0.000000,1,26,34.217968,0.479,0.4822,5.158391,63.368